name: Stub run
on: 
  pull_request:
    branches:
    - master
jobs:
  nf-stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - run: echo "#0" > nextflow.log && nextflow run ${GITHUB_WORKSPACE} -stub --samplesheet ${GITHUB_WORKSPACE}/examples/CTG_SampleSheet.csv --outdir ${GITHUB_WORKSPACE} -profile local_dev
